name: andriod-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-andriod-srccds:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build-cstrike
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        sudo apt update;sudo apt upgrade;sudo apt install ccache
        unzip android-ndk-r10e-linux-x86_64.zip > /dev/null
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -o /dev/null
        tar xvf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz > /dev/null
        mv clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04 clang/
        export PATH=$(pwd)/clang/bin:$PATH
        mv android-ndk-r10e ndk/
        export ANDROID_NDK_HOME=$(pwd)/ndk
        mkdir ./andriod
        git submodule init;git submodule update
        ./waf configure -T release -d --togles --android=aarch64,host,21 --prefix=./andriod --disable-warns --build-game=cstrike 
        ./waf install --target=client,server
        
        cat build/config.log >./andriod/iffo.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: cstrike-64
        path: ./andriod
        if-no-files-found: error

  build-arm64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 11
        export PATH="/usr/lib/llvm-11/bin:$PATH"
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
        export NDK_HOME=$PWD/android-ndk-r10e/
        mkdir ./andriod
        git submodule init;git submodule update
        ./waf configure -T release -8 --togles --android=aarch64,host,21 --prefix=./andriod --disable-warns 
        ./waf install
        cat build/config.log > ./andriod/info.txt
    - uses: actions/upload-artifact@v3
      with:
        name: aarch64-srceng
        path: ./andriod
        if-no-files-found: error
