 name: andriod

on:
  push:
    branches:
      "*"
  pull_request:
    branches:
      "*"

jobs:
  build-andriod-arm64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 11
        export PATH="/usr/lib/llvm-11/bin:$PATH"
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
        export NDK_HOME=$PWD/android-ndk-r10e/
        mkdir ./andriod
        ./waf configure -T release -8 --togles --android=aarch64,host,21 --prefix=./andriod --disable-warns
    - uses: actions/upload-artifact@v3
      with:
        name: Source Engine-andriod-arm64
        path: ./andriod
        if-no-files-found: error

  build-ds:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build ds
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 11
        export PATH="/usr/lib/llvm-11/bin:$PATH"
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
        export NDK_HOME=$PWD/android-ndk-r10e/
        mkdir ./andriod
        ./waf configure -T release -d --togles --android=armeabi-v7a-hard,host,21 --prefix=./andriod --disable-warns
    - uses: actions/upload-artifact@v3
      with:
        name: Srcds andriod
        path: ./andriod
        if-no-files-found: error
