name: Build

on: [push, pull_request]

jobs:
  build-linux-i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build linux-i386
      run: |
        scripts/build-ubuntu-i386.sh
    - uses: actions/upload-artifact@v3
      with:
        name: smod-linux32
        path: ./to_upload
        if-no-files-found: error

  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh
    - uses: actions/upload-artifact@v3
      with:
        name: smod-linux64
        path: ./to_upload
        if-no-files-found: error

  Build-apk-for-android:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Cloning apk repo and preparing for building
      run: |
        git clone https://github.com/ItzVladik/modlauncher-waf
        sudo apt-get update
        sudo apt-get install -f -y openjdk-8-jre zip apksigner
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh
    - name: Build-android-aarch64
      run: |
        scripts/build-android-aarch64.sh    
    - name: Finally build apk
      run: |
        scripts/build-apk.sh 
    - name: Rename apk
      run: |
         mv modlauncher-waf/build/android/mod-signed.apk smod-release.apk

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: smod-apk
        path: smod-release.apk

  build-windows-win32:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        #
        git submodule init;git submodule update
        ./waf.bat configure -T release --prefix=./win --disable-warns --build-game=smod

        ./waf.bat install

    - uses: actions/upload-artifact@v3
      with:
        name: smod-win32
        path: ./win
        if-no-files-found: error
        
  build-windows-win64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        #
        git submodule init;git submodule update
        ./waf.bat configure -T release --prefix=./win --disable-warns --build-game=smod -8
        
        ./waf.bat install

    - uses: actions/upload-artifact@v3
      with:
        name: smod-win64
        path: ./win
        if-no-files-found: error
  
  build-macos-amd64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macos-amd64
      run: |
        scripts/build-macos-amd64.sh