name: Build

on: [push, pull_request]

jobs:
  build-linux-i386:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-i386
      run: |
        scripts/build-ubuntu-i386.sh

  build-linux-amd64:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh

  build-android-armv7a:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Installing clang11
      run: |
        curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        tar -xvf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        export PATH=$PWD/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04/bin:$PATH
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh
        
  build-android-aarch64:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Installing clang11
      run: |
        curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        tar -xvf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz 
        export PATH=$PWD/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04/bin:$PATH    
    - name: Build android-aarch64
      run: |
        chmod +x scripts/build-android-aarch64.sh
        scripts/build-android-aarch64.sh        

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --build-game=hl2sb
        ./waf.bat build

  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T release --build-game=hl2sb -8
        ./waf.bat build

  build-dedicated-linux-i386:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-i386
      run: |
        scripts/build-ubuntu-i386.sh -d

  build-dedicated-linux-amd64:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh -d
