name: andriod-2023

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-mod-64bit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build-hl2mp_cstrike_hl1
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        sudo apt update;sudo apt upgrade;sudo apt install ccache
        unzip android-ndk-r10e-linux-x86_64.zip > /dev/null
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -o /dev/null
        tar -xf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        export PATH="$PWD/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04/bin:$PATH"

        mv android-ndk-r10e ndk/
        export ANDROID_NDK_HOME=$(pwd)/ndk
        mkdir ./andriod
        mkdir ./andriod/hl2mp
        ./waf configure -T release -8 --togles --android=aarch64,host,21 --prefix=./andriod/hl1mp --disable-warns --build-game=hl2mp
        #test hldms
        ./waf install --target=client,server -j4 --strip
        #mv ./andriod/lib ./andriod/cstrike
        cat build/config.log >./andriod/info.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: 64bit-hl2mp_fix
        path: ./andriod
        if-no-files-found: error


  build-mod-32bit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build-hl2mp_cstrike_hl1
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        sudo apt update;sudo apt upgrade;sudo apt install ccache
        unzip android-ndk-r10e-linux-x86_64.zip > /dev/null
        wget https://apt.llvm.org/llvm.sh
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -o /dev/null
        tar -xf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        export PATH="$PWD/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04/bin:$PATH"
        mv android-ndk-r10e ndk/
        export ANDROID_NDK_HOME=$(pwd)/ndk
        mkdir ./andriod
        mkdir ./andriod/hl2mp
        mkdir ./andriod/hl1
        mkdir ./andriod/hl1mp
        mkdir ./andriod/cstrike
        git submodule init;git submodule update
        ./waf configure -T release --togles --android=armeabi-v7a-hard,host,21 --prefix=./andriod/hl1mp --disable-warns --build-game=hl2mp
        #test hldms
        ./waf install --target=client,server -j4 --strip
        #mv ./andriod/lib ./andriod/cstrike
        cat build/config.log >./andriod/info.txt
        
    - uses: actions/upload-artifact@v3
      with:
        name: 32bit-hl2mp_fix
        path: ./andriod
        if-no-files-found: error

  