name: Build

on: [push, pull_request]

jobs:
  build-linux-i386:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build linux-i386
      run: |
        scripts/build-ubuntu-i386.sh
    - uses: actions/upload-artifact@v3
      with:
        name: missinginfo-linux32
        path: ./to_upload
        if-no-files-found: error

  build-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh
    - uses: actions/upload-artifact@v3
      with:
        name: missinginfo-linux64
        path: ./to_upload
        if-no-files-found: error

  build-missinginfo-android:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3

    - name: build

      run: |

        wget https://apt.llvm.org/llvm.sh

        chmod +x llvm.sh

        sudo ./llvm.sh 11

        export PATH="/usr/lib/llvm-11/bin:$PATH"

        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null

        unzip android-ndk-r10e-linux-x86_64.zip

        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/

        export NDK_HOME=$PWD/android-ndk-r10e/

        mkdir ./android

        ./waf  configure -T release --build-game=missinginfo --android=aarch64,host,21 --target=../aarch64 -8 --disable-warns --prefix=./android/arm64

        ./waf install -j4 --target=server,client

        cat build/config.log > ./andriod/info.txt
        ./waf  configure -T release --build-game=missinginfo --android=armeabi-v7a-hard,host,21 --target=../armeabi --disable-warns --prefix=./android/arm32
        ./waf install -j4 --target=server,client

    - uses: actions/upload-artifact@v3

      with:

        name: missinginfo-android

        path: ./android

        if-no-files-found: error

  build-windows-win32:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        #
        git submodule init;git submodule update
        ./waf.bat configure -T release --prefix=./win --disable-warns --build-game=missinginfo
        
        ./waf.bat install
#        cat build/config.log > ./win/info.txt I dont' think that it is useful
    - uses: actions/upload-artifact@v3
      with:
        name: missinginfo-win32
        path: ./win
        if-no-files-found: error
        
  build-windows-win64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        #
        git submodule init;git submodule update
        ./waf.bat configure -T release --prefix=./win --disable-warns --build-game=missinginfo -8
        
        ./waf.bat install
#        cat build/config.log > ./win/info.txt I dont' think that it is useful
    - uses: actions/upload-artifact@v3
      with:
        name: missinginfo-win64
        path: ./win
        if-no-files-found: error
