name: android

on: [push, pull_request]

jobs:

  Build-apk-for-android:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3

    - name: Cloning apk repo and preparing for building

      run: |

        ls

        

    - name: Build android-armv7a

      run: |

        git submodule init && git submodule update

        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null

        unzip android-ndk-r10e-linux-x86_64.zip

        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/

        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -o /dev/null

        tar -xf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz

        export PATH="$PWD/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04/bin:$PATH"

        ./waf configure -T release --build-game=hl2sb --android=armeabi-v7a-hard,host,21 --target=../armeabi-v7a --disable-warns &&

        ./waf install -j4 --destdir=./HL2SB

        ./waf configure -T release --build-game=hl2sb --android=aarch64,host,21 --prefix=./HL2SB --disable-warns &&

        ./waf install -j4

        #scripts/build-android-armv7a.sh

    - name: Build-android-aarch64

      run: |

        #scripts/build-android-aarch64.sh    

    - name: Finally build apk

      run: |

        #scripts/build-apk.sh    

        

    - name: Rename apk

      run: |

         #mv HL2SB-launcher/build/android/mod-signed.apk hl2sb-release-dev.apk

    - name: 'Upload Artifact'

      uses: actions/upload-artifact@v3

      with:

        name: hl2sb-andriod-dev

        path: ./HL2SB
