name: Tests

on: [push, pull_request]

jobs:
  # build-linux-i386:
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v3
    # - name: Build linux-i386
      # run: |
        # scripts/build-ubuntu-i386.sh
    # - uses: actions/upload-artifact@v3
      # with:
        # name: missinginfo-linux32
        # path: ./to_upload
        # if-no-files-found: error

  # build-linux-amd64:
    # runs-on: ubuntu-20.04

    # steps:
    # - uses: actions/checkout@v3
    # - name: Build linux-amd64
      # run: |
        # scripts/build-ubuntu-amd64.sh
    # - uses: actions/upload-artifact@v3
      # with:
        # name: missinginfo-linux64
        # path: ./to_upload
        # if-no-files-found: error

  setup:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Cloning apk repo and preparing for building
      run: |
        #git clone https://github.com/ItzVladik/modlauncher-waf
        #sudo apt-get update
        #sudo apt-get install -f -y openjdk-8-jre zip apksigner
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        sudo apt update;sudo apt upgrade;sudo apt install ccache
        unzip android-ndk-r10e-linux-x86_64.zip > /dev/null
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 11
        export PATH="/usr/lib/llvm-11/bin:$PATH"
        mv android-ndk-r10e ndk/
        mkdir ./andriod
        export ANDROID_NDK_HOME=$(pwd)/ndk
        ./waf configure -T debug --android=armeabi-v7a-hard,4.9,21 --disable-warns --prefix=./android/arm
        ./waf install -j8
    - name: Build android-armv7a
      run: |
        git submodule init && git submodule update
        export ANDROID_NDK_HOME=$(pwd)/ndk
        #scripts/build-android-armv7a.sh
        ./waf configure -T release --android=armeabi-v7a-hard,4.9,21 --disable-warns --prefix=./android/arm32
        ./waf install -j8
        # ./waf configure -T debug --build-game=hl2 --android=aarch64,host,21 -8 --disable-warns --prefix=./android/arm64
        # ./waf install -j8 --strip

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: hl2-android
        path: ./android






































