name: Build cl_dll server
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  windows_engine_x86:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create output dir
      run: mkdir ./out
    - name: Configure build
      run: ./waf configure -T release --build-game=cstrike --prefix=./out
    - name: Build
      run: ./waf install
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: engine_x86_cstrike
        path: ./out
  windows_hl2_cldl_x86:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create output dir
      run: mkdir ./out
    - name: Configure build
      run: ./waf configure -T release --build-game=hl2 --prefix=./out
    - name: Build
      run: ./waf install --target=client,server
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows_hl2_cl_dll_x86
        path: ./out
  windows_dods_cl_dll_x86:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create output dir
      run: mkdir ./out
    - name: Configure build
      run: ./waf configure -T release --build-game=dod --prefix=./out
    - name: Build
      run: ./waf install --target=client,server
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows_dod_cl_dll_x86
        path: ./out
  windows_only_dedicated_x86:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Create output dir
      run: mkdir ./out
    - name: Configure build
      run: ./waf configure -T release -d --build-game=dod --prefix=./out
    - name: Build
      run: ./waf install
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows_dod_dedicated_x86
        path: ./out
